# Generated by Django 3.2.4 on 2021-06-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyDataUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('beneficiaries_assisted_males', models.IntegerField()),
                ('beneficiaries_assisted_females', models.IntegerField()),
                ('cash_value', models.IntegerField()),
                ('country_iso3', models.CharField(max_length=3)),
            ],
        ),
    ]
